# Generated by Django 3.1.6 on 2021-02-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_app', '0002_auto_20210202_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='creation_date',
            field=models.DateTimeField(),
        ),
    ]
